### ISSUE TITLE
socket.io error message, when running in production mode

### ISSUE THREAD

**Issue by ghost** [channikhabra/yarr#1]
My firebug/shell console are all bombarded with continuously printed error messages,

``` javascript
"NetworkError: 404 Not Found - http://localhost:8080/socket.io/?EIO=3&transport=polling&t=1437734568622-21"
?EIO=3&...8622-21
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/socket.io/?EIO=3&transport=polling&t=1437734568622-21. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

Can this be turned off/patched?

**Comment by bitspook** [comment]
Hey,

Really sorry I missed adding that in 0-setup step. 

Those socket requests are made for webpack-dev-server which do the live-reload stuff. We remove it when we build for production. 

Quick work-through: Instead of using `webpack -p`, use `NODE_ENV=production webpack -p` (I hope you're using bash or zsh, we are just setting an environment-variable)

You can check the `webpack.config.js` for details.

This tutorial is not 100% done actually, I'll try to finish it tonight.

**Comment by ghost** [comment]
sorry man. i forgot to confirm, it works.. thanks...
