### ISSUE TITLE
Why jQuery.ajax over Rx.DOM.ajax?

### ISSUE THREAD

**Issue by adrianfalleiro** [channikhabra/yarr#2]
Not really an issue - but wondering why you're using jQuery.ajax over Rx.DOM.ajax?

**Comment by bitspook** [comment]
Hey Adrian,

There's no particular reason for that except that I wanted to have something commonly used as an example of how Rx plays well with jquery. I originally built this app for giving a workshop in jQuery conf 2015. I chose Ajax because jquery promises are infamously non compliant with the A spec and all.

—

**Comment by adrianfalleiro** [comment]
Ah, makes sense - thanks
