### ISSUE TITLE
Router for multiple pages?

### ISSUE THREAD

**Issue by kfei** [channikhabra/yarr#23]
Hi @channikhabra,

First of all thank you for this great repository. I spent almost a half day on it and found out it's really awesome. Got a real world experience of reactive programming by following your step by step tutorial.

Now I would like to play with it furthermore. For example, a setting page for user preference. Hence we need a **router** to coordinate the renderers for multiple pages. 

Just wonder how would you implement that, and still keep it reactive, declarative and framework-less?

Thanks.

**Comment by bitspook** [comment]
Hey @kfei,

Glad you liked the tutorial.

I haven't given this much thought, but here's what come from over the top of my head about a router. 

Basically the job of the router is akin to a `filter` operation. It would have a root view (the layout) and have a filter for views in it. 
We can create a Router Observable which is a derivation from pushstate event, and starts with a default value, the view based on current location (for `/` it would be the view for sidebar + list of posts). Then on every change in location, we map the current location to a different view, so if user navigates to `/settings`, instead of returning 'posts' view (or component as we call it), we return the settings view which is then rendered by the layout (the root view).
This would make the initial version of the router, call it pre-alpha. From here on we can improvise and create more sophisticated Router. Once we have a clear idea of how routes shall be structured, next step would be implementing nested routes (basically a recursive router, should not be very difficult). Eventually we can go for a more sophisticated abstraction over this which would make creating routes feel like rest of the world. 

Hope I am making sense. What do you think of this approach? Do you have something else in mind?

Thanks for showing interest in further exploration. I myself have plans for a Yarr v2. I created this tutorial kind of hastily, it's really less than 10% of what I had actually planned. I hope I can get some time soon to work on this. Gotta pay my bills too :stuck_out_tongue: 

I hope I haven't killed your interest by replying so late. Like I said, I am going very busy these days.

**Comment by kfei** [comment]
@channikhabra, Thanks for your hints.

I like your approach. It did the trick without too much efforts to implement.

Now I just can't wait to dig into Yarr v2! :smile:

**Comment by bitspook** [comment]
> Now I just can't wait to dig into Yarr v2! :smile:

It sure feel good to hear that 😅

Yarr was originally supposed to be "The Reader" that I want to use for myself. That's what I intend to make for Yarr v2. I'll make it a tutorial because I like making tutorials. It'll be a RSS reader, Newsletter Reader, and a social network (word "yaar" means "friend" in Punjabi/Hindi). Imagine a fully decentralised social network (or partially decentralised for realtime updates). We already have more than what it would take to accomplish this. Imagine you share (status) updates by writing blog posts (and hence generating entries in RSS feeds). That is what twitter is basically. Micro-blogging. It'll be a lot of fun to twist the norms of social-media. It's possible to fully integrate such system with facebook/twitter/github/random internet forums/what-not. I sure need it for reddit. I go to reddit for /r/programming etc, and get lost in wormhole of naughty subreddits.
You get to discover new content by following other people. Your likes/shares is just another RSS feed etc. A simple, fully-under-user's-control system. It will sure be plenty of fun to make it yourself and make it 100% offline compatible (a browser extension, or standalone electron app) and fully self-hosted. I've lived a long time with little to no connectivity, offline is what I seek first in anything I want to make for myself :stuck_out_tongue: 

If only I had enough free time to do that right now 😅

Anyway, I am closing this issue now.

**Comment by kfei** [comment]
Hi @channikhabra, I've added this repo to my [handpicked resources](https://milkr.io/kfei/RxJS-and-Reactive-Programming) to help people learn Rx. It's my understanding of **yarr**, so please correct me if I made something wrong. Thank you again for making this wonderful repo! :smile:

**Comment by bitspook** [comment]
Thanks for adding it to your list @kfei : )
